apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: tvlk
  namespace: elastic-system
spec:
  version: 7.13.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
  auth:
    fileRealm:
    - secretName: tvlk-es-filerealm-secret